services:
  # device_agent:
  #   image: spaneng/doover_device_agent:apps
  #   network_mode: host

  # sample_simulator:
  #   build: ./sample
  #   network_mode: host
  #   restart: unless-stopped
  #   depends_on:
  #     - device_agent
  #   environment:
  #     - APP_KEY=sim_app_key

  sia-test-bench:
    build: ../
    network_mode: host
    restart: unless-stopped
    # depends_on:
    #   - device_agent
    #   - sample_simulator
    environment:
      - APP_KEY=sia_test_bench_1
      # - CONFIG_FP=/app/simulators/app_config.json
      # - DDA_URI=192.168.100.97:50051
